### ISSUE TITLE
stream funktioniert nicht

### ISSUE THREAD

**Issue by Bunchy88** [MrKrabat/plugin.video.wakanim#1]
Hi, erstmal danke für das Addon.
Leider bin ich nicht in der Lage meine gekauften Folgen zu schauen,.
Ich bekomme immer die Meldung:du brauchst einen Premium Account oder musst die Folgen gekauft haben.

**Comment by MrKrabat** [comment]
Hi,
da hab vergessen etwas zu berücksichtigen^^

https://github.com/MrKrabat/plugin.video.wakanim/blob/master/resources/lib/netapi.py#L245
Die markierte Zeile 245 bis 248 auskommentieren, einfach ein # davor machen (in deiner Installierten Version werden die Zeilennummern anders sein!)
Die Datei findest du unter .kodi/addons/plugin.video.wakanim/resources/lib/ , der Ort des .kodi Ordners ist abhängig davon worauf die Kodi nutzt.

dann sollte es gehen - jedoch werden "kostenlos zu sehende Episoden" jetzt versucht abzuspielen was fehlschlagen wird.

**Comment by Bunchy88** [comment]
Vielen Dank läuft nun wunderbar

**Comment by Bunchy88** [comment]
oder doch nicht. Habe eine folge angemacht und es lief auch erst wie es soll.
Nachdem ich aber eine neue Folge anmachen wollte, bekomme ich immer eine Fehlermeldung und der Stream startet nicht.
12:23:29.984 T:780   ERROR: XFILE::CDirectory::GetDirectory - Error getting
12:24:35.796 T:8108   ERROR: Previous line repeats 9 times.
12:24:35.796 T:8108 WARNING: Attempt to use invalid handle -1
12:24:36.486 T:8108   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "C:\Users\Kim\AppData\Roaming\Kodi\addons\plugin.video.wakanim\default.py", line 35, in <module>
                                                wakanim.main()
                                              File "C:\Users\Kim\AppData\Roaming\Kodi\addons\plugin.video.wakanim\resources\lib\wakanim.py", line 60, in main
                                                check_mode(args)
                                              File "C:\Users\Kim\AppData\Roaming\Kodi\addons\plugin.video.wakanim\resources\lib\wakanim.py", line 101, in check_mode
                                                netapi.startplayback(args)
                                              File "C:\Users\Kim\AppData\Roaming\Kodi\addons\plugin.video.wakanim\resources\lib\netapi.py", line 252, in startplayback
                                                matches = re.search(regex, html).group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
12:24:47.967 T:9996  NOTICE: Storing total System Uptime
12:24:47.967 T:9996  NOTICE: Saving settings
12:24:47.974 T:9996  NOTICE: Saving skin settings
12:24:47.977 T:9996  NOTICE: stop all
12:24:47.977 T:9996  NOTICE: stop player
12:24:47.977 T:9996  NOTICE: ES: Stopping event server
12:24:47.977 T:9996  NOTICE: stopping upnp
12:24:48.565 T:1780  NOTICE: ES: UDP Event server stopped
12:24:48.880 T:9996  NOTICE: clean cached files!
12:24:48.884 T:9028  NOTICE: Skin Helper Service --> Shutdown requested !
12:24:48.886 T:9028  NOTICE: Skin Helper Service --> Skin Helper Service version 1.1.3 stopped
12:24:48.973 T:9996  NOTICE: closing down remote control service
12:24:49.143 T:9996  NOTICE: stopped
12:24:49.344 T:9996  NOTICE: destroy
12:24:49.344 T:9996  NOTICE: unload skin
12:24:49.349 T:9996 WARNING: CGUITextureManager::Cleanup: Having to cleanup texture lists/focus.png
12:24:49.379 T:9996  NOTICE: unload sections
12:24:49.381 T:9996  NOTICE: special://profile/ is mapped to: special://masterprofile/
12:24:49.387 T:9996  NOTICE: application stopped...

**Comment by MrKrabat** [comment]
Könntest du mir sagen um welchen Anime und Episode es sich handelt?

**Comment by Bunchy88** [comment]
sind beide gekauft und kings funktionierte beim ersten versuch und danach funktionierten beide nicht mehr.
kings-game-the-animation-omu
vanishing-line-omu

**Comment by MrKrabat** [comment]
Könntest du eine der Episoden einmal im Browser öffnen und dann den gesamten Seitenquelltext kopieren und z.B. über pastebin senden?

Er findet die Streaming Dateien nicht und deswegen kommt der crasht

**Comment by Bunchy88** [comment]
[vanishing_line_(omu).txt](https://github.com/MrKrabat/plugin.video.wakanim/files/1366810/vanishing_line_.omu.txt)

**Comment by MrKrabat** [comment]
Ok habs gefunden das Problem...
die haben den "Video reaktivieren" Müll wie Akibapass.

Bislang hatte ich das noch nicht gehabt (hab vorhin erst eine Episode zum Test gekauft)
Hab den fix gleich drin ;)

**Comment by Bunchy88** [comment]
Dachte ich mir auch gerade als ich es reaktivieren musste das es wohl daran liegt.

**Comment by MrKrabat** [comment]
Okay frag mich nicht warum, aber die haben plötzlich einige nervige Features von Akibapass übernommen...
Aber keine Sorge, muss nur ein bissel von Akibapass zu Wakanim Porten 👍

**Comment by MrKrabat** [comment]
Hab ein Update jetzt in Github

bitte einmal als ZIP installieren und testen
https://github.com/MrKrabat/plugin.video.wakanim/archive/master.zip

**Comment by Bunchy88** [comment]
Habe es gerade getestet, Video mehrmals gestartet und es läuft perfekt.
Vielen Dank für das schnelle update.
