### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by petersen77** [MrKrabat/plugin.video.wakanim#18]
No login possible (OSMC 2019.4-1, Kodi 18.2)
[kodi.log](https://github.com/MrKrabat/plugin.video.wakanim/files/3124774/kodi.log)

**Comment by Acreen** [comment]
Same problem with LibreElec 9.0.1 Kodi 18.1 Leia.

The login data is valid for sure since it is working at the computer.

[kodi.log](https://github.com/MrKrabat/plugin.video.wakanim/files/3125336/kodi.log)

**Comment by MrKrabat** [comment]
Thanks for reporting it.
Wakanim has made changes to the login process, an update is on its way.

**Comment by gdott9** [comment]
Thanks for the fix, it works for me !

**Comment by Acreen** [comment]
Working here, too. Thx a lot!

**Comment by petersen77** [comment]
Working again. Thanks

**Comment by MrKrabat** [comment]
The update is now in the Kodi repository and will be delivered automatically.
