### ISSUE TITLE
Don't sync the Episode with Wakanim Account

### ISSUE THREAD

**Issue by kev-dev1** [MrKrabat/plugin.video.wakanim#24]
I've use Kodi 18.5 Leia and the Wakanim addon. But when i watch a Episode by Wakanim over Kodi don't sync the last Time or the next Episode with my Account.

**Comment by MrKrabat** [comment]
For me playtime sync is working as expected, maybe it was fixed unintentionally.
Or you disabled playtime sync in the addon settings?

**Comment by kev-dev1** [comment]
The Playtime Sync is activate. But he not synchro the Episode
