### ISSUE TITLE
Image pixel when streaming video (1080p)

### ISSUE THREAD

**Issue by Besur** [MrKrabat/plugin.video.wakanim#28]
Hi,

I have some video playback problem in 1080p (and the same on 720p too), a lot of miss pixel are falling apart...

screen of it : https://i.imgur.com/av3NDNV.png (all the video is not like this, juste some parts...)
speedtest : https://i.imgur.com/OCTupIH.png

do you have some video options or addon option to avoid this ?

**Comment by MrKrabat** [comment]
InputstreamAdaptive addon is used for video decryption and decoding. You should definitely check out their settings.
It has some settings for bandwith, you can read more about this [here](https://github.com/peak3d/inputstream.adaptive#bandwidth-and-resolution).

**Comment by Besur** [comment]
i have a strong bandwidth at home, and still laying with all params let the same parts with the same problems, if you can try and tell me for the episode 9 of BOFURI at 1m19s if you have the same issue : https://i.imgur.com/8fuO9Px.png

**Comment by Besur** [comment]
And it's always at the same time, same parts of video, same artefact again and again

**Comment by Besur** [comment]
??

**Comment by Besur** [comment]
is that possible to transcode video with buffer or cache so i can enjoy the video without this artefacts ?

**Comment by MrKrabat** [comment]
I don't know if Kodi/InputstreamAdaptive has settings for buffering. My addon only feeds Kodi with the video URL, everything else is done by Kodi/InputstreamAdaptive.
