### ISSUE TITLE
Download Episodes

### ISSUE THREAD

**Issue by ScarVite** [MrKrabat/plugin.video.wakanim#29]
Is it possible for you to implement a download feature,with which you can download episodes from wakanim, with a active premium subscription, f.e. the latest aired episodes

**Comment by MrKrabat** [comment]
I dont know if this has changed, but you can only download episodes you bought. Premium does not permit to download episodes.

**Comment by KyKyIIIKuH** [comment]
now premium has the ability to download episodes

**Comment by ScarVite** [comment]
Since you can download the Episodes on mobile i thought there might be a possibility for you to implement this feature so that i can copy the (mp4 would be perfect) onto a usb and watch them on my tv

**Comment by MrKrabat** [comment]
This addon does not use the closed source API of wakanim. Therefore this is not an "app" and you cannot download episodes.

Downloaded episodes are probably encrypted, so you cannot copy or view them outside the wakanim app. In the same way that Netflix and Amazon do.

Anything in this direction is probably a violation of their terms of service.
